### ISSUE TITLE
Should this work with the newest kernel?

### ISSUE THREAD

**Issue by NF3RN0** [philenotfound/rpi_elecfreaks_22_tft_dt_overlay#1]
I have the lastest Raspbian Lite image and I am trying to get the TFT to output console. From my understanding the latest kernel includes notro's driver for the ili9341.

What I have done so far:

Installed from raspberrypi.org the lastest Raspbian Lite release on my SD.

I followed your wiring diagram. 

Copied your overlay to the overlays folder.

Edited both the cmdline.txt and config.txt

`dmesg | grep graphics
[   10.542744] graphics fb1: fb_ili9341 frame buffer, 320x240, 150 KiB video memory, 16 KiB DMA buffer memory, fps=33, spi0.0 at 32 MHz`

My understanding is that from this point the console should show on boot to the TFT display. All that displays is a white screen, so atleast the display is turning on.

Your thoughts? Am I missing something on my install? 

Cheers.

**Comment by NF3RN0** [comment]
So I figured out that my problem was the wires I was using were not getting a good connection. So I used better jumper wires. 

Works perfectly now.

**Comment by philenotfound** [comment]
White screen typically indicates an issue with communications, ie the ILI9341 gets power but isn't initialized.
